Project 4: Desktop version
yaseerokino/personal-portfolio pull request #5
Opened 2021-07-22 23:29 UTC by yaseerokino

#Features Added ♻️ 

- Added Desktop Responsiveness
- Updated Index.html structure

2021-07-22 23:55 UTC, Shaher-11 requested changes
#### Hello @yaseerokino,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Check the comments below:point_down:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-22 23:55 UTC, Shaher-11 commented on index.html
> +          <li><a href="#">Contact</a></li>
Add some space on the left and right side of the nav items 
#### Original design
![right](https://user-images.githubusercontent.com/58376020/126722571-6d78371e-4be8-4a1e-b392-7938fdfaf3dd.png)

#### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/126722593-1b340ab5-89ad-43a0-afa7-3143b6621ffc.png)

2021-07-22 23:55 UTC, Shaher-11 commented on index.html
> -        </ul>
You need to switch the position of the image from the right to left as shown below
#### Original design
![right](https://user-images.githubusercontent.com/58376020/126722821-5eecf9b9-88dd-482e-a8e5-ef471ea73392.png)

#### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/126722848-6c3a3208-8d7c-487e-92da-bb6f1a15f24a.png)

2021-07-22 23:55 UTC, Shaher-11 commented on index.html
> +                  <button type="submit">Get in Touch</button>
Center the button as shown in the original design

2021-07-23 08:09 UTC, hemant-soni-vst-au4 requested changes
Hi @yaseerokino and @OLIPLICHE, 

Good job so far! 👍 
There is still one issue that you need to work on to go to the next project but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-23 08:09 UTC, hemant-soni-vst-au4 commented on index.html
> +            </ul>
- [ ] On desktop view the image and content and not aligned properly. All other projects are aligned properly. In this picture is taking the full space of `<div>`. Kindly try to fix it. 

![image](https://user-images.githubusercontent.com/53019916/126754094-b696e9de-8eda-4105-9e5b-0f0e15881200.png)

2021-07-23 13:32 UTC, yaseerokino commented on index.html
> +            </ul>
@hemant-soni-vst-au4 Please could you further explain exactly what you mean, because I don't understand exactly what you mean. Additionally, I made all the required changes requested by @Shaher-11.

2021-07-23 14:59 UTC, hemant-soni-vst-au4 commented on index.html
> +            </ul>
- For your second project inside the work section.  Your description and image of projects are not aligned properly like the other projects. Check the image.

![image](https://user-images.githubusercontent.com/53019916/126800969-be6d2d85-744d-47b9-b226-dff48398c3b7.png)
 

Happy Coding. 🚀

2021-07-23 17:50 UTC, ahmetbozaci approved these changes
# STATUS: Approved  🥳    🥳 

## Hello @yaseerokino  ✋🏼 Your project is complete!  There is nothing else to say other than... it's time to merge it and delete the branch. You can submit this project in your dashboard.


### OPTIONAL SUGGESTIONS

#### These are optional 


- [ ]  Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start). 

- [ ] For DRY css you should combine duplicate properties. 
Example you can create class `.d-flex { display: flex}` and use this class in html file.

- For more information about DRY principles you can check this [article](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- Also you can refresh your knowledge about "html and css best practices" in [curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)


### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/xT8qBepJQzUjXpeWU8/giphy.gif)



___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-23 19:39 UTC, merged